import mods.ItemStages;

<ore:oreTitanium>.add(<contenttweaker:mercury_titanium>);
<ore:oreBoron>.add(<contenttweaker:mars_boron>);
<ore:orePlatinum>.add(<contenttweaker:mars_platinum>);
<ore:oreUranium>.add(<contenttweaker:mars_uranium>);
<ore:oreLithium>.add(<contenttweaker:sol_asteroids_lithium>);
<ore:oreNickel>.add(<contenttweaker:sol_asteroids_nickel>);
<ore:oreTungsten>.add(<contenttweaker:sol_asteroids_tungsten>);
<ore:oreMagnesium>.add(<contenttweaker:venus_magnesium>);
<ore:oreZinc>.add(<contenttweaker:venus_zinc>);
<ore:oreCopper>.add(<contenttweaker:mist_up_copper>);
<ore:oreFluorite>.add(<contenttweaker:mist_down_fluorite>);
<ore:oreBoron>.add(<contenttweaker:mist_down_boron>);
<ore:oreUranium>.add(<contenttweaker:mist_down_uranium>);
<ore:oreThorium>.add(<contenttweaker:mist_down_thorium>);
<ore:oreBoron>.add(<contenttweaker:glacidus_middle_boron>);
<ore:oreSilver>.add(<contenttweaker:glacidus_middle_silver>);
<ore:oreLead>.add(<contenttweaker:glacidus_middle_lead>);
<ore:oreGold>.add(<contenttweaker:glacidus_middle_gold>);
<ore:oreRedstone>.add(<contenttweaker:glacidus_bottom_redstone>);
<ore:oreQuartz>.add(<contenttweaker:glacidus_bottom_quartz>);
<ore:oreNickel>.add(<contenttweaker:proxima_b_nickel>);
<ore:oreTungsten>.add(<contenttweaker:proxima_b_tungsten>);
<ore:oreThorium>.add(<contenttweaker:proxima_b_thorium>);
<ore:orePlatinum>.add(<contenttweaker:proxima_b_platinum>);
<ore:oreUranium>.add(<contenttweaker:barnarda_c_uranium>);
<ore:oreThorium>.add(<contenttweaker:barnarda_c_thorium>);
<ore:oreBoron>.add(<contenttweaker:barnarda_c_boron>);
<ore:oreSilver>.add(<contenttweaker:barnarda_c_silver>);
<ore:oreLead>.add(<contenttweaker:barnarda_c_lead>);
<ore:oreSalt>.add(<contenttweaker:barnarda_c_salt>);
<ore:oreTitanium>.add(<contenttweaker:barnarda_c_titanium>);
<ore:oreZinc>.add(<contenttweaker:midnight_zinc>);
<ore:oreFluorite>.add(<contenttweaker:midnight_fluorite>);
<ore:oreTin>.add(<contenttweaker:midnight_tin>);
<ore:oreCoal>.add(<contenttweaker:midnight_coal>);
<ore:oreMagnesium>.add(<contenttweaker:midnight_magnesium>);
<ore:oreQuartz>.add(<contenttweaker:midnight_quartz>);

ItemStages.addItemStage("mercury", <contenttweaker:mercury_titanium>);
ItemStages.addItemStage("mars", <contenttweaker:mars_boron>);
ItemStages.addItemStage("mars", <contenttweaker:mars_platinum>);
ItemStages.addItemStage("mars", <contenttweaker:mars_uranium>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_lithium>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_nickel>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_tungsten>);
ItemStages.addItemStage("venus", <contenttweaker:venus_magnesium>);
ItemStages.addItemStage("venus", <contenttweaker:venus_zinc>);
ItemStages.addItemStage("mist", <contenttweaker:mist_up_copper>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_fluorite>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_boron>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_uranium>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_thorium>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_boron>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_silver>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_lead>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_gold>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_bottom_redstone>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_bottom_quartz>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_nickel>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_tungsten>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_thorium>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_platinum>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_uranium>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_thorium>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_boron>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_silver>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_lead>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_salt>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_titanium>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_zinc>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_fluorite>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_tin>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_coal>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_magnesium>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_quartz>);