import mods.ItemStages;

<ore:oreTitanium>.add(<contenttweaker:mercury_titanium>);
<ore:oreBoron>.add(<contenttweaker:mars_boron>);
<ore:orePlatinum>.add(<contenttweaker:mars_platinum>);
<ore:oreUranium>.add(<contenttweaker:mars_uranium>);
<ore:oreLithium>.add(<contenttweaker:sol_asteroids_lithium>);
<ore:oreNickel>.add(<contenttweaker:sol_asteroids_nickel>);
<ore:oreTungsten>.add(<contenttweaker:sol_asteroids_tungsten>);
<ore:oreDilithium>.add(<contenttweaker:sol_asteroids_dilithium>);
<ore:oreMagnesium>.add(<contenttweaker:venus_magnesium>);
<ore:oreZinc>.add(<contenttweaker:venus_zinc>);
<ore:oreCopper>.add(<contenttweaker:mist_up_copper>);
<ore:oreAluminum>.add(<contenttweaker:mist_up_aluminum>);
<ore:oreFluorite>.add(<contenttweaker:mist_down_fluorite>);
<ore:oreBoron>.add(<contenttweaker:mist_down_boron>);
<ore:oreUranium>.add(<contenttweaker:mist_down_uranium>);
<ore:oreThorium>.add(<contenttweaker:mist_down_thorium>);
<ore:oreBoron>.add(<contenttweaker:glacidus_middle_boron>);
<ore:oreSilver>.add(<contenttweaker:glacidus_middle_silver>);
<ore:oreLead>.add(<contenttweaker:glacidus_middle_lead>);
<ore:oreGold>.add(<contenttweaker:glacidus_middle_gold>);
<ore:oreRedstone>.add(<contenttweaker:glacidus_bottom_redstone>);
<ore:oreQuartz>.add(<contenttweaker:glacidus_bottom_quartz>);
<ore:oreDilithium>.add(<contenttweaker:glacidus_bottom_dilithium>);
<ore:oreNickel>.add(<contenttweaker:proxima_b_nickel>);
<ore:oreTungsten>.add(<contenttweaker:proxima_b_tungsten>);
<ore:oreThorium>.add(<contenttweaker:proxima_b_thorium>);
<ore:orePlatinum>.add(<contenttweaker:proxima_b_platinum>);
<ore:oreTritanium>.add(<contenttweaker:proxima_b_tritanium>);
<ore:oreUranium>.add(<contenttweaker:barnarda_c_uranium>);
<ore:oreThorium>.add(<contenttweaker:barnarda_c_thorium>);
<ore:oreBoron>.add(<contenttweaker:barnarda_c_boron>);
<ore:oreSilver>.add(<contenttweaker:barnarda_c_silver>);
<ore:oreLead>.add(<contenttweaker:barnarda_c_lead>);
<ore:oreSalt>.add(<contenttweaker:barnarda_c_salt>);
<ore:oreTitanium>.add(<contenttweaker:barnarda_c_titanium>);
<ore:oreFluorite>.add(<contenttweaker:midnight_fluorite>);
<ore:oreTin>.add(<contenttweaker:midnight_tin>);
<ore:oreCoal>.add(<contenttweaker:midnight_coal>);
<ore:oreMagnesium>.add(<contenttweaker:midnight_magnesium>);
<ore:oreQuartz>.add(<contenttweaker:midnight_quartz>);
<ore:oreDilithium>.add(<contenttweaker:midnight_dilithium>);
<ore:oreCoal>.add(<contenttweaker:tauceti_ocean_coal>);
<ore:oreLithium>.add(<contenttweaker:tauceti_ocean_lithium>);
<ore:oreCopper>.add(<contenttweaker:tauceti_ocean_copper>);
<ore:oreIron>.add(<contenttweaker:tauceti_ocean_iron>);
<ore:oreSalt>.add(<contenttweaker:tauceti_ocean_salt>);
<ore:oreZinc>.add(<contenttweaker:tauceti_deep_zinc>);
<ore:oreTritanium>.add(<contenttweaker:tauceti_deep_tritanium>);
<ore:oreLithium>.add(<contenttweaker:tauceti_deep_lithium>);
<ore:oreIron>.add(<contenttweaker:tauceti_deep_iron>);
<ore:oreGold>.add(<contenttweaker:tauceti_deep_gold>);
<ore:oreTungsten>.add(<contenttweaker:tauceti_deep_tungsten>);
<ore:oreAluminum>.add(<contenttweaker:tauceti_deep_aluminum>);
<ore:oreNickel>.add(<contenttweaker:tauceti_deep_nickel>);
<ore:oreBoron>.add(<contenttweaker:tauceti_deep_boron>);
<ore:oreLead>.add(<contenttweaker:tauceti_deep_lead>);
<ore:oreSilver>.add(<contenttweaker:tauceti_deep_silver>);
<ore:oreThorium>.add(<contenttweaker:tauceti_deep_thorium>);
<ore:oreUranium>.add(<contenttweaker:tauceti_deep_uranium>);
<ore:oreCopper>.add(<contenttweaker:space_copper>);
<ore:oreIron>.add(<contenttweaker:space_iron>);
<ore:oreAluminum>.add(<contenttweaker:space_aluminum>);
<ore:oreLead>.add(<contenttweaker:space_lead>);
<ore:oreRedstone>.add(<contenttweaker:space_redstone>);
<ore:oreGold>.add(<contenttweaker:space_gold>);
<ore:oreDiamond>.add(<contenttweaker:space_diamond>);
<ore:oreTin>.add(<contenttweaker:space_tin>);
<ore:oreSilver>.add(<contenttweaker:space_silver>);
<ore:oreMagnesium>.add(<contenttweaker:space_magnesium>);
<ore:oreUranium>.add(<contenttweaker:space_uranium>);
<ore:oreThorium>.add(<contenttweaker:space_thorium>);
<ore:oreLithium>.add(<contenttweaker:space_lithium>);
<ore:oreGlowstone>.add(<contenttweaker:space_glowstone>);
<ore:oreUranium>.add(<contenttweaker:janssen_uranium>);
<ore:oreThorium>.add(<contenttweaker:janssen_thorium>);
<ore:oreSapphire>.add(<contenttweaker:janssen_sapphire>);
<ore:oreDiamond>.add(<contenttweaker:janssen_diamond>);
<ore:oreRuby>.add(<contenttweaker:janssen_ruby>);

ItemStages.addItemStage("mercury", <contenttweaker:mercury_titanium>);
ItemStages.addItemStage("mars", <contenttweaker:mars_boron>);
ItemStages.addItemStage("mars", <contenttweaker:mars_platinum>);
ItemStages.addItemStage("mars", <contenttweaker:mars_uranium>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_lithium>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_nickel>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_tungsten>);
ItemStages.addItemStage("sol_asteroids", <contenttweaker:sol_asteroids_dilithium>);
ItemStages.addItemStage("venus", <contenttweaker:venus_magnesium>);
ItemStages.addItemStage("venus", <contenttweaker:venus_zinc>);
ItemStages.addItemStage("mist", <contenttweaker:mist_up_copper>);
ItemStages.addItemStage("mist", <contenttweaker:mist_up_aluminum>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_fluorite>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_boron>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_uranium>);
ItemStages.addItemStage("mist", <contenttweaker:mist_down_thorium>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_boron>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_silver>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_lead>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_middle_gold>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_bottom_redstone>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_bottom_quartz>);
ItemStages.addItemStage("glacidus", <contenttweaker:glacidus_bottom_dilithium>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_nickel>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_tungsten>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_thorium>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_platinum>);
ItemStages.addItemStage("proxima_b", <contenttweaker:proxima_b_tritanium>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_uranium>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_thorium>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_boron>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_silver>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_lead>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_salt>);
ItemStages.addItemStage("barnarda_c", <contenttweaker:barnarda_c_titanium>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_fluorite>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_tin>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_coal>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_magnesium>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_quartz>);
ItemStages.addItemStage("midnight", <contenttweaker:midnight_dilithium>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_ocean_coal>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_ocean_lithium>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_ocean_copper>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_ocean_iron>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_ocean_salt>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_zinc>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_tritanium>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_lithium>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_iron>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_gold>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_tungsten>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_aluminum>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_nickel>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_boron>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_lead>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_silver>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_thorium>);
ItemStages.addItemStage("tauceti_f", <contenttweaker:tauceti_deep_uranium>);
ItemStages.addItemStage("janssen", <contenttweaker:janssen_uranium>);
ItemStages.addItemStage("janssen", <contenttweaker:janssen_thorium>);
ItemStages.addItemStage("janssen", <contenttweaker:janssen_sapphire>);
ItemStages.addItemStage("janssen", <contenttweaker:janssen_diamond>);
ItemStages.addItemStage("janssen", <contenttweaker:janssen_ruby>);