#loader contenttweaker

import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Block;
import mods.contenttweaker.ResourceLocation;
import crafttweaker.game.IGame;

function createOre(name as string, toolLevel as int) {
  var ore = VanillaFactory.createBlock(name, <blockmaterial:rock>);
  ore.setBlockResistance(6.0);
  ore.setToolClass("pickaxe");
  ore.setTranslucent(false);
  ore.setToolLevel(toolLevel);
  ore.register();
}

createOre("mercury_titanium", 2);
createOre("mars_boron", 2);
createOre("mars_platinum", 2);
createOre("mars_uranium", 2);
createOre("sol_asteroids_lithium", 2);
createOre("sol_asteroids_nickel", 2);
createOre("sol_asteroids_tungsten", 2);
createOre("venus_magnesium", 2);
createOre("venus_zinc", 2);
createOre("mist_up_copper", 2);
createOre("mist_down_fluorite", 2);
createOre("mist_down_boron", 2);
createOre("mist_down_uranium", 2);
createOre("mist_down_thorium", 2);
createOre("glacidus_middle_boron", 2);
createOre("glacidus_middle_silver", 2);
createOre("glacidus_middle_lead", 2);
createOre("glacidus_middle_gold", 2);
createOre("glacidus_bottom_redstone", 2);
createOre("glacidus_bottom_quartz", 2);
createOre("proxima_b_nickel", 2);
createOre("proxima_b_tungsten", 2);
createOre("proxima_b_thorium", 2);
createOre("proxima_b_platinum", 2);
createOre("barnarda_c_uranium", 2);
createOre("barnarda_c_thorium", 2);
createOre("barnarda_c_boron", 2);
createOre("barnarda_c_silver", 2);
createOre("barnarda_c_lead", 2);
createOre("barnarda_c_salt", 2);
createOre("barnarda_c_titanium", 2);
createOre("midnight_zinc", 2);
createOre("midnight_fluorite", 2);
createOre("midnight_tin", 2);
createOre("midnight_coal", 2);
createOre("midnight_magnesium", 2);
createOre("midnight_quartz", 2);
createOre("space_copper", 2);
createOre("space_iron", 2);
createOre("space_aluminum", 2);
createOre("space_lead", 2);
createOre("space_redstone", 2);
createOre("space_gold", 2);
createOre("space_diamond", 2);
createOre("space_tin", 2);
createOre("space_silver", 2);
createOre("space_magnesium", 2);
createOre("space_uranium", 2);
createOre("space_thorium", 2);
createOre("space_lithium", 2);
createOre("space_glowstone", 2);
createOre("janssen_uranium", 2);
createOre("janssen_thorium", 2);
createOre("janssen_sapphire", 2);
createOre("janssen_diamond", 2);
createOre("janssen_ruby", 2);