name = "Daedalian 2"
author = "Dakedres"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6723c6b93954efb7361cdf85fb08cfb55f2468ea6cb07b1f7c7923fe079c2105"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
