name = "Daedalian 2"
author = "Dakedres"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83fe6ade95b1662a943fa81e14b0ece1b8e3e1ec512a7fad0365c10aa2915c6f"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
