name = "Daedalian 2"
author = "Dakedres"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d273d7ca7ad6cf12527e9a58842eba4a2f2ea166ebb87f809834715fed4a8a3"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
