name = "Daedalian 2"
author = "Dakedres"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be37b66ca038cfbd7095bdccbbfdd4b44509d4ee128eb10de3ccc89e1f77f7c0"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
