name = "Daedalian 2"
author = "Dakedres"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7462318556f6fa1c6c57ac6088b8c8defe4138fc9667510c9884ecb5137bcc4d"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
