name = "Daedalian 2"
author = "Dakedres"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c5027bc2459711112da496481e5be83297e3dadac7269cfa5b5b49db75c7033"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
